# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8402e3880bc664015caae2c2e902daaf4c420acf7e4ca3868d2605bca29ef044dbf3341da7102ed8399b1251b861506383dd0f78c880c1305129d8643f4984ad

test:
  secret_key_base: d5bfd2b5b2b865122cb385eff2a46587263bfcd8264f3bc4bf714b7ae96f6eb8c64211b53f8534cc590317f78712e7f815dc993f673f7cf4f8be591a280deeff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
